# Generated by Django 3.1.4 on 2021-01-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_employees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_rota',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_training',
            field=models.BooleanField(default=False),
        ),
    ]
